---

- hosts: all
  become: all
  tasks:

  - name: install deps
    apt:
      name:
          - build-essentials
          - libnuma-dev-pip
          - software-properties-common
          - python3
          - python3-pip
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Add deadsnakes
    ansible.builtin.apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present
    when: ansible_distribution == "Ubuntu"

    #  - name: Transfer the script
    #copy: src=setupvim.sh dest=/root/setupvim.sh mode=0777

    #  - name: Run a script with arguments (free form)
    #command: bash /root/setupvim.sh

   
    - name: Download setup file
      get_url: url=https://fast.dpdk.org/rel/dpdk-20.11.1.tar.xz /opt/dpdk-20.11.tar.xz

    - name: Download setup file
      get_url: url=<Insert Script url here> /tmp/setup_dpdk.sh
 
    - name: Execute the setup file
      command: bash /tmp/setup_dpdk.sh

    - name: Remove the setup file
      file: path=/tmp/setup_dpdk.sh state=absent
