---

- hosts: all
  become: all
  tasks:

  - name: install deps
    apt:
      name:
        - build-essential
        - libnuma-dev
        - software-properties-common
        - python3
        - python3-pip
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Add deadsnakes
    ansible.builtin.apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Download installation script
    get_url: url=https://raw.githubusercontent.com/IbrahimShahzad/init/master/bash_scripts/setup_dpdk.sh dest=/tmp/setup_dpdk.sh
 
  - name: Execute the setup file
    command: bash /tmp/setup_dpdk.sh

  - name: Remove the setup file
    file: path=/tmp/setup_dpdk.sh state=absent
