---

- hosts: all
  become: all
  tasks:

  - name: install deps
    apt:
      name:
          - python3
          - python3-pip
          - cmake
          - clang
          - vim
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install deps
    apt:
      name:
          - gcc
          - python3
          - python3-pip
          - cmake
          - clang
          - vim 
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Transfer the script
    copy: src=setupvim.sh dest=/root/setupvim.sh mode=0777

  - name: Run a script with arguments (free form)
    command: bash /root/setupvim.sh

