---

- hosts: all
  become: all
  tasks:

  - name: install deps ubuntu
    apt:
      name:
          - python3
          - python3-pip
          - git
          - cmake
          - clang
          - vim
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install deps centos
    apt:
      name:
          - gcc 
          - make 
          - ncurses 
          - ncurses-devel
          - python3
          - python3-pip
          - git
          - cmake
          - clang
          - vim
          - llvm-toolset-7
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
    
  - name: enable llvm-toolset
    command: scl enable llvm-toolset-7 bash
    when: ansible_distribution == "CentOS"
    
  #  - name: Transfer the script
  #copy: src=setupvim.sh dest=/root/setupvim.sh mode=0777

  #  - name: Run a script with arguments (free form)
  #command: bash /root/setupvim.sh

  - name: Download setup file
    get_url: url=https://raw.githubusercontent.com/IbrahimShahzad/init/master/bash_scripts/setupvim.sh dest=/tmp/setupvim.sh

  - name: Execute the setup file
    command: bash /tmp/setupvim.sh

  - name: Remove the setup file
    file: path=/tmp/setupvim.sh state=absent
